# Generated by Django 5.0.6 on 2024-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_account_number_account_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
